spring:
  application:
    name: feign-server
server:
  port: 8765
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka
feign:
  hystrix:
    enabled: true

# 请求处理的超时时间
# ribbon.ReadTimeout=120000
# 请求连接的超时时间
# ribbon.ConnectTimeout=30000
